blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/1337rod/Offline-Minecraft-Skin-Converter/discussions
    about: Ask and discuss anything about the project.
  - name: Report a security vulnerability
    url: https://github.com/1337rod/Offline-Minecraft-Skin-Converter/security/policy
    about: Report security issues directly to the maintainer.
